//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Finsoft.Common.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    [System.ServiceModel.ServiceContract]
    // Se agrega propiedad para excluir el modelo de la revisión del code analysis
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Finsoft", "1.0.0.0")]
    public  interface IAudit_MonitorChange
    {
         long ObjectId { get; set; }
         string EventType { get; set; }
         string SchemaName { get; set; }
         string ObjectName { get; set; }
         string ObjectType { get; set; }
         string EventDate { get; set; }
         string SystemUser { get; set; }
         string CurrentUser { get; set; }
         string OriginalUser { get; set; }
         string DatabaseName { get; set; }
         string TSSQLCode { get; set; }
         Nullable<int> spid { get; set; }
         string HostName { get; set; }
         string AppName { get; set; }
    #region FinsoftModel
     IDictionary<String, Object> ExtendedProperties { set; get; }
        #endregion
    }
}